# nixpacks.toml
# Nixpacks configuration for Next.js 14 project "lider"
# Compatible with Node.js 22 and Coolify deployment

# List of additional providers (leave empty if none)
[providers]
providers = []

# Base image used for building the project
buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1741046653"

# Environment variables for production
[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

# Setup phase: install required system packages and Node environment
[phases.setup]
nixPkgs = [
  "nodejs_22",      # Node.js 22
  "npm-9_x",        # NPM 9
  "openssl"         # OpenSSL required by some Node packages
]
nixOverlays = [
  "https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"
]
aptPkgs = ["curl", "wget"]
cmds = []
cacheDirectories = []
paths = []

# Install phase: install dependencies and generate Prisma client
[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci",           # Clean install of dependencies
  "npm run postinstall" # Run Prisma generate
]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

# Build phase: build Next.js project
[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = [
  ".next/cache",
  "node_modules/.cache"
]

# Start phase: start the application
[phases.start]
dependsOn = ["build"]
cmds = ["npm run start"]
