# nixpacks.toml - Configuração completa para seu projeto Node.js 22

[env]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
NEXTAUTH_URL = "https://lider.fegsoft.com.br"
NEXTAUTH_SECRET = "zJb9orA-ycf5TkxBqFuKlZRMs_6a6vposC3FRd9qjIs="
URL_DO_BANCO_DE_DADOS = "postgres://postgres:%40Ap210484@144.22.137.177:15432/postgres"
SOURCE_COMMIT = "HEAD"

[phases.setup]
nixPkgs = [
    "curl",
    "nodejs_22",
    "npm",
    "openssl",
    "wget"
]
nixOverlays = [
    "https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"
]
aptPkgs = [
    "curl",
    "wget"
]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm ci"
]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
dependsOn = ["install"]
cmds = [
    "npm run build"
]
cacheDirectories = [
    ".next/cache",
    "node_modules/.cache"
]

[phases.start]
cmd = "npm run start"

[build]
buildCommand = "npm run build"
startCommand = "npm run start"
