# nixpacks.toml - Versão corrigida e otimizada

[phases.setup]
# Pacotes a serem instalados durante a configuração
nixPkgs = [
  "curl"
  "nodejs-22_x"
  "npm-10_x"
  "openssl"
  "wget"
]

[phases.build]
# Comandos para construir seu app
command = "npm install && npm run build"

[phases.start]
# Comando para iniciar o app
command = "npm run start"

[env]
# Variáveis de ambiente
NODE_ENV = "production"
PORT = "3000"

[ports]
# Porta que o Nixpacks deve expor
http = 3000
