# nixpacks.toml - versão simplificada para Next.js 14 + Node 22

[[providers]]
name = "nodejs"
version = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]
cmds = []

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci", "npm run postinstall"]
cacheDirectories = ["/root/.npm"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = [".next/cache"]

[phases.start]
dependsOn = ["build"]
cmds = ["npm run start"]
