# Lista de provedores (Node.js neste caso)
providers = ["nodejs"]

# Imagem base usada para construir a aplicação
buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1741046653"

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.setup]
dependsOn = []
# Atualizando para Node.js 22
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"
aptPkgs = ["curl", "wget"]
cmds = []
cacheDirectories = []
paths = []

[phases.start]
dependsOn = ["build"]
cmds = ["npm run start"]
