# Nixpacks config for Node.js (Next.js) app

providers = []

buildImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1741046653"

[env]
CI = true
NIXPACKS_METADATA = "node"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = false
SOURCE_COMMIT = "HEAD"
DATABASE_URL = "postgres://postgres:%40Ap210484@144.22.137.177:15432/postgres"
NEXTAUTH_URL = "https://lider.fegsoft.com.br"
NEXTAUTH_SECRET = "zJb9orA-ycf5TkxBqFuKlZRMs_6a6vposC3FRd9qjIs="

[phases.setup]
cmds = []
dependsOn = []
cacheDirectories = []
paths = []
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"
aptPkgs = ["curl", "wget"]

[phases.install]
cmds = ["npm ci"]
dependsOn = ["setup"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]
cacheDirectories = [".next/cache", "node_modules/.cache"]

[phases.start]
cmd = "npm run start"
dependsOn = ["build"]
